// Autogenerated by SourceCodeGenerator

using System;
using DN.WebApi.Shared.DTOs.CRM;
using FluentValidation;

namespace DN.WebApi.Application.Validators.CRM
{
    public class CreateNoteRequestValidator : CustomValidator<CreateNoteRequest>
    {
        public CreateNoteRequestValidator()
        {
            RuleFor(p => p.Subject).MaximumLength(75).NotEmpty();
            RuleFor(p => p.Message).MaximumLength(255).NotEmpty();
        }
    }
}