// Autogenerated by SourceCodeGenerator

using System;
using DN.WebApi.Shared.DTOs.CRM;
using FluentValidation;

namespace DN.WebApi.Application.Validators.CRM
{
    public class CreatePersonRequestValidator : CustomValidator<CreatePersonRequest>
    {
        public CreatePersonRequestValidator()
        {
            RuleFor(p => p.Name).MaximumLength(75).NotEmpty();
            RuleFor(p => p.Age).GreaterThanOrEqualTo(0).NotEmpty();
        }
    }
}