// Autogenerated by SourceCodeGenerator

using System;
using DN.WebApi.Shared.DTOs.CRM;
using FluentValidation;

namespace DN.WebApi.Application.Validators.CRM
{
    public class UpdateNoteRequestValidator : CustomValidator<UpdateNoteRequest>
    {
        public UpdateNoteRequestValidator()
        {
            RuleFor(p => p.Subject).MaximumLength(75).NotEmpty();
            RuleFor(p => p.Message).MaximumLength(75).NotEmpty();
            RuleFor(p => p.PersonId);
            RuleFor(p => p.Id).NotEmpty();
        }
    }
}