// Autogenerated by SourceCodeGenerator

using System;
using System.Collections.Generic;

namespace DN.WebApi.Shared.DTOs.CRM
{
    public class CompanyDto : IDto
    {
        public Guid Id { get; set; }
        public string CompanyName { get; set; }
        public string TenantKey { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public Guid LastModifiedBy { get; set; }
    }
}