// Autogenerated by SourceCodeGenerator

using System;

namespace DN.WebApi.Shared.DTOs.CRM
{
    public class CreateCompanyRequest : IMustBeValid
    {
        public Guid Id { get; set; }
        public string CompanyName { get; set; }
    }
}