// Autogenerated by SourceCodeGenerator

using System;
using System.Collections.Generic;

namespace DN.WebApi.Shared.DTOs.CRM
{
    public class NoteDto : IDto
    {
        public Guid Id { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Guid PersonId { get; set; }
    }
}