// Autogenerated by SourceCodeGenerator

using System;
using System.Collections.Generic;

namespace DN.WebApi.Shared.DTOs.CRM
{
    public class NoteDto : IDto
    {
        public Guid Id { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Guid PersonId { get; set; }
        public string TenantKey { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public Guid LastModifiedBy { get; set; }
    }
}