// Autogenerated by SourceCodeGenerator

using System;
using System.Collections.Generic;

namespace DN.WebApi.Shared.DTOs.CRM
{
    public class PersonDto : IDto
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public DateTime DateOfBirth { get; set; }
        public Guid CompanyId { get; set; }
    }
}