// Autogenerated by SourceCodeGenerator

using System;

namespace DN.WebApi.Shared.DTOs.CRM
{
    public class UpdateNoteRequest : IMustBeValid
    {
        public Guid Id { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Guid PersonId { get; set; }
    }
}