// Autogenerated by SourceCodeGenerator

using DN.WebApi.Shared.DTOs.CRM;
using DN.WebApi.Application.Abstractions.Services;
using DN.WebApi.Application.Wrapper;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace DN.WebApi.Application.Abstractions.Services.CRM
{
    public interface INoteService : ITransientService
    {
        Task<Result<NoteDetailsDto>> GetNoteDetailsAsync(Guid id);
        Task<PaginatedResult<NoteDto>> GetNotesAsync(NoteListFilter filter);
        Task<Result<NoteDto>> GetByIdUsingDapperAsync(Guid id);
        Task<Result<Guid>> CreateNoteAsync(CreateNoteRequest request);
        Task<Result<Guid>> UpdateNoteAsync(UpdateNoteRequest request, Guid id);
        Task<Result<Guid>> DeleteNoteAsync(Guid id);
    }
}