// Autogenerated by SourceCodeGenerator

using DN.WebApi.Shared.DTOs.CRM;
using DN.WebApi.Application.Abstractions.Services;
using DN.WebApi.Application.Wrapper;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace DN.WebApi.Application.Abstractions.Services.CRM
{
    public interface IPersonService : ITransientService
    {
        Task<Result<PersonDetailsDto>> GetPersonDetailsAsync(Guid id);
        Task<PaginatedResult<PersonDto>> GetPersonsAsync(PersonListFilter filter);
        Task<Result<PersonDto>> GetByIdUsingDapperAsync(Guid id);
        Task<Result<Guid>> CreatePersonAsync(CreatePersonRequest request);
        Task<Result<Guid>> UpdatePersonAsync(UpdatePersonRequest request, Guid id);
        Task<Result<Guid>> DeletePersonAsync(Guid id);
    }
}